
# forground n background
foreground #e3c7fc
background #09090d

# black
color0 #6272a4
color8 #6272a4

# red
color1 #F37F97
color9 #FF4971

# green
color2 #5ADECD
color10 #18E3C8

# yellow
color3 #8897F4
color11 #8897F4

# blue
color4 #bd93f9
color12 #bd93f9

# magenta
color5 #ff79c6
color13 #ff79c6

# cyan
color6 #8be9fd
color14 #8be9fd

# white
color7 #bfaae3
color15 #bfaae3

#/* special colors */
#[258] = "#c6b3e6", /* foreground */
